#!/bin/bash
# app_ids.txt contains all app_ids to be scraped
INPUT=$*

echo "$INPUT"

# Log output (https://blog.tratif.com/2023/01/09/bash-tips-1-logging-in-shell-scripts/)
LOGFILE="steamdb_scraper.log"
exec 3>&1 1>>"$LOGFILE" 2>&1
trap "echo 'ERROR: An error occurred during execution, check \""$LOGFILE\"" for details.' >&3" ERR
trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Is)]  "; set -x' DEBUG

echo "Starting ${0##*/}..."

# Fail if any command fails (https://stackoverflow.com/a/32684221/17771525)
set -e
set -o pipefail

# Check if app_ids.txt exists
if [ ! -f app_ids.txt ]; then
    HEADER="# DO NOT EDIT THIS FILE\n# This file is automatically generated by add_app_id.sh\n# Run add_app_id.sh for more info\n"
    echo -e "$HEADER" >>app_ids.txt
fi

for app_id in $INPUT; do
    echo "Adding app ID $app_id..." >&3
    # Check if input is an integer (https://stackoverflow.com/a/806923/17771525)
    if [[ ! "$app_id" =~ ^[0-9]+$ ]]; then
        echo "$app_id is not an integer, skipping..."
        continue
    fi

    # Check if app_ids.txt contain same app_id
    if grep -q "$app_id" app_ids.txt; then
        echo "App ID $app_id already exists"
    else
        # Scrape app_id from steamdb and save to database
        ./fetch_steamdb_html.sh "$app_id" | ./scrape_game_data.sh | ./save_game_data.sh

        # Append app_id to app_ids.txt
        echo "$app_id" >>app_ids.txt

        echo "App ID $app_id successfully added!" >&3
    fi
done

echo "${0##*/} complete..." >&3
